FORMAT: 1A

# TimeEntry api
TimeEntry API is a time entry service.

# Group BookedTimeEntry
TimeEntry related resources of the **TimeEntry API**

## BookedTimeEntry List [/booked-time-entries{?start_date,end_date}]

### List all BookedTimeEntries [GET]
+ Parameters

    + start_date (optional, date, `2014-05-05T00:00:00Z`) ... Date `start_date` of the BookedTimeEntry. Has example value.
    + end_date (optional, date, `2014-05-05T00:00:00Z`) ... Date `end_date` of the BookedTimeEntry. Has example value.
    
+ Request

    + Header
            
            Authorization: Bearer <token>
            Accept: vnd.intertech.v1+json
            If-None-Match: W/"11-2535484157"

+ Response 200 (application/json)

    + Header
        
            Request-Id: <UUID>
            ETag: W/"11-2535484157" 
        
    + Body

            [{
              "id": 1, "user": { "id": "31EC2020-3AEA-4069-A2DD-08002B30309D" }, "date": "2014-05-10T00:00:00Z", "hours": 8, "note": "I worked all day long on Wednesday.", "read_only": false,
              "allocation": { "id": 2, "client": "State of Minnesota DEED", "project": "MN Works", "task": "Development" }
            }, {
              "id": 2, "user": { "id": "31EC2020-3AEA-4069-A2DD-08002B30309D" }, "date": "2014-05-10T00:00:00Z", "hours": 8, "note": "I worked all day long on Thursday.", "read_only": true,
              "allocation": { "id": 2, "client": "Agribank", "project": "Titaniun", "task": "Testing" }
            }]

## BookedTimeEntry [/booked-time-entries]

### Create a BookedTimeEntry [POST]
+ Request (application/json)

    + Header

            Authorization: Bearer <token>
            Accept: vnd.intertech.v1+json

    + Body

            { "user": { "id": "31EC2020-3AEA-4069-A2DD-08002B30309D" }, "date": "2014-05-07T00:00:00", "hours": 8, "note": "I worked all day long on Friday.", "allocation": { "id": 1 } }

+ Response 201 (application/json)
    
    + Header
        
            Request-Id: <UUID>
    
    + Body

            { "id": 3, "user": { "id": "31EC2020-3AEA-4069-A2DD-08002B30309D" }, "date": "2014-05-07T00:00:00", "hours": 8, "note": "I worked all day long on Friday.", "allocation": { "id": 1 } }


## BookedTimeEntry [/booked-time-entries/{id}]
A single BookedTimeEntry object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the BookedTimeEntry to perform action with. Has example value.

### Update a BookedTimeEntry [PUT]
+ Request (application/json)

    + Header

            Authorization: Bearer <token>
            Accept: vnd.intertech.v1+json

    + Body

            { "id": 1, "user": { "id": "31EC2020-3AEA-4069-A2DD-08002B30309D" }, "date": "2014-05-10T00:00:00Z", "hours": 8, "note": "I worked all day long on Saturday.", "allocation": { "id": 1 } }

+ Response 200

    + Header
        
            Request-Id: <UUID>
            
    + Body

            { "id": 3, "user": { "id": "31EC2020-3AEA-4069-A2DD-08002B30309D" }, "date": "2014-05-10T00:00:00Z", "hours": 8, "note": "I worked all day long on Friday.", "allocation": { "id": 1 } }            

### Remove a BookedTimeEntry [DELETE]
+ Response 200

    + Header
        
            Request-Id: <UUID>
            
    + Body

            { "id": 3, "user": { "id": "31EC2020-3AEA-4069-A2DD-08002B30309D" }, "date": "2014-05-10T00:00:00Z", "hours": 8, "note": "I worked all day long on Friday.", "allocation": { "id": 1 } }            

# Group Allocation
Allocation related resources of the **TimeEntry API**

## Allocation Collection [/allocations]

### List all Allocations [GET]

+ Request

    + Header
            
            Authorization: Bearer <token>
            Accept: vnd.intertech.v1+json
            If-None-Match: W/"11-2535484157"
            
+ Response 200 (application/json)
    
    + Header
        
            Request-Id: <UUID>
            ETag: W/"11-2535484157" 
    
    + Body
    
            [{
              "id": 1, "client": "State of Minnesota DEED", "project": "MN Works", "task": "Development"
            }, {
              "id": 2, "client": "Agribank", "project": "Titaniun", "task": "Testing"
            }]

## Allocation [/allocations/{id}]
A single Allocation object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Allocation to perform action with. Has example value.

### Retrieve an Allocation [GET]
+ Request

    + Header
            
            Authorization: Bearer <token>
            Accept: vnd.intertech.v1+json
            If-None-Match: W/"11-2535484157"


+ Response 200 (application/json)
    + Header
        
            Request-Id: <UUID>
            ETag: W/"11-2535484157" 
    
    + Body

            { "id": 1, "client": "State of Minnesota DEED", "project": "MN Works", "task": "Development" }

# Group Authentication
Authentication endpoints

## Token [/token]
Authentication Endpoint to get a bearer token for use in other api endpoints.

## Retrieve a token [POST]
+ Request

    + Header
    
            Accept: vnd.intertech.v1+json
            Content-Type: application/json
    + Body
    
            { "grant_type": "saml", "token": "--base64 encoded token--" }
            
+ Response 200 (application/json)

    + Header
    
            Request-Id: <UUID>
    
    + Body
            
            { "access_token": "--bearer token--", "token_type": "bearer", "name": "Luke Vader", "email": "a@b.c" }