FORMAT: 1A
HOST: http://www.google.com

# TimeEntry api
TimeEntry API is a time entry service.

# Group BookedTimeEntry
TimeEntry related resources of the **TimeEntry API**

## BookedTimeEntry Collection [/bookedTimeEntries]
### List all BookedTimeEntry [GET]
+ Request

    + Header
            
            Authorization: bearer <token>
+ Response 200 (application/json)

        [{
          "id": 1, "userId": 1, "date": "2014-05-05T00:00:00", "hours": 8, "note": "I worked all day long on Wednesday.",
          "allocation": { "client": "State of Minnesota DEED", "project": "MN Works", "task": "Development" }
        }, {
          "id": 2, "userId": 1, "date": "2014-05-05T00:00:00", "hours": 8, "note": "I worked all day long on Thursday.",
          "allocation": { "client": "Agribank", "project": "Titaniun", "task": "Testing", id }
        }]

### Create a BookedTimeEntry [POST]
+ Request (application/json)

    + Header

            Authorization: bearer <token>

    + Body

            { "userId": 1, "date": "2014-05-07T00:00:00", "hours": 8, "note": "I worked all day long on Friday.", "allocationId": 1 }

+ Response 201 (application/json)

        { "id": 3, "userId": 1, "date": "2014-05-07T00:00:00", "hours": 8, "note": "I worked all day long on Friday.", "allocationId": 1 }


### Update a BookedTimeEntry [PUT]
+ Request (application/json)

    + Header

            Authorization: bearer <token>

    + Body

            { "id": 4, "userId": 1, "date": "2014-05-10T00:00:00", "hours": 8, "note": "I worked all day long on Saturday.", "allocationId": 1 }

+ Response 204

## BookedTimeEntry [/bookedTimeEntries/{id}]
A single BookedTimeEntry object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the BookedTimeEntry to perform action with. Has example value.

### Retrieve a BookedTimeEntry [GET]
+ Request

    + Header
            
            Authorization: bearer <token>

+ Response 200 (application/json)

    + Body

            { "id": 1, "userId": 1, "date": "2014-05-05T00:00:00", "hours": 8, "note": "I worked all day long on Wednesday.", "allocation": { "client": "State of Minnesota DEED", "project": "MN Works", "task": "Development" }}

### Remove a BookedTimeEntry [DELETE]
+ Response 204
